// ==========================================
// AUTO-GENERATED — DO NOT EDIT MANUALLY
// Run: npm run db:types
// ==========================================
// This file will be auto-generated by Supabase CLI.
// For now, we define a minimal placeholder.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      user_profiles: {
        Row: {
          id: string;
          user_id: string;
          full_name: string;
          display_name: string | null;
          avatar_url: string | null;
          phone: string | null;
          role: "admin" | "editor" | "viewer" | "developer";
          timezone: string;
          language: string;
          notification_preferences: Json;
          is_active: boolean;
          last_active_at: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: Omit<
          Database["public"]["Tables"]["user_profiles"]["Row"],
          "id" | "created_at" | "updated_at"
        >;
        Update: Partial<
          Database["public"]["Tables"]["user_profiles"]["Insert"]
        >;
      };
      kanban_columns: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          color: string | null;
          position: number;
          card_limit: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["kanban_columns"]["Row"],
          "id" | "created_at" | "updated_at"
        >;
        Update: Partial<
          Database["public"]["Tables"]["kanban_columns"]["Insert"]
        >;
      };
      kanban_cards: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          card_type: "single_post" | "campaign";
          column_id: string;
          position_in_column: number;
          created_by: string;
          responsible_user_id: string | null;
          due_date: string | null;
          completed_at: string | null;
          priority: "low" | "medium" | "high" | "urgent" | null;
          tags: string[];
          platforms: string[];
          content_type: string | null;
          is_blocked: boolean;
          blocked_reason: string | null;
          moved_to_column_at: string;
          metadata: Json;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: Omit<
          Database["public"]["Tables"]["kanban_cards"]["Row"],
          "id" | "created_at" | "updated_at" | "moved_to_column_at"
        >;
        Update: Partial<
          Database["public"]["Tables"]["kanban_cards"]["Insert"]
        >;
      };
      // TODO: Run `npm run db:types` to generate complete types
      // after applying all Supabase migrations
    };
    Views: {};
    Functions: {};
    Enums: {
      calendar_item_type: "event" | "delivery" | "creation" | "task" | "meeting";
      calendar_item_status: "pending" | "in_progress" | "completed" | "cancelled";
      card_type: "single_post" | "campaign";
      post_status: "draft" | "awaiting_approval" | "approved" | "scheduled" | "published" | "failed" | "rejected";
      post_type: "image" | "video" | "carousel" | "story" | "reels" | "short" | "newsletter";
      asset_type: "image" | "video" | "audio" | "document" | "template";
      asset_source: "upload" | "ai_generated" | "emusys" | "canva" | "event";
      approval_status: "pending" | "approved" | "rejected" | "needs_revision";
      campaign_type: "organic" | "paid_social" | "paid_search" | "mixed";
      campaign_status: "draft" | "active" | "paused" | "completed" | "cancelled";
      execution_status: "queued" | "running" | "completed" | "failed" | "cancelled";
      log_level: "debug" | "info" | "warning" | "error" | "critical";
      notification_type: "whatsapp" | "email" | "in_app" | "push";
      notification_priority: "low" | "normal" | "high" | "urgent";
    };
  };
}
