// ==========================================
// AUTO-GENERATED — DO NOT EDIT MANUALLY
// Run: npm run db:types
// ==========================================
// This file will be auto-generated by Supabase CLI.
// For now, we define a minimal placeholder.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      user_profiles: {
        Row: {
          id: string;
          user_id: string;
          full_name: string;
          display_name: string | null;
          avatar_url: string | null;
          phone: string | null;
          role: "admin" | "editor" | "viewer" | "developer";
          timezone: string;
          language: string;
          notification_preferences: Json;
          is_active: boolean;
          is_admin: boolean;
          whatsapp_jid: string | null;
          bio: string | null;
          specializations: string[];
          last_active_at: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: Omit<
          Database["public"]["Tables"]["user_profiles"]["Row"],
          "id" | "created_at" | "updated_at" | "is_admin" | "is_active" | "specializations"
        > & {
          is_admin?: boolean;
          is_active?: boolean;
          specializations?: string[];
        };
        Update: Partial<
          Database["public"]["Tables"]["user_profiles"]["Insert"]
        >;
      };
      kanban_columns: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          color: string | null;
          position: number;
          card_limit: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["kanban_columns"]["Row"],
          "id" | "created_at" | "updated_at"
        >;
        Update: Partial<
          Database["public"]["Tables"]["kanban_columns"]["Insert"]
        >;
      };
      kanban_cards: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          card_type: "single_post" | "campaign";
          column_id: string;
          position_in_column: number;
          created_by: string;
          responsible_user_id: string | null;
          due_date: string | null;
          completed_at: string | null;
          priority: "low" | "medium" | "high" | "urgent" | null;
          tags: string[];
          platforms: string[];
          content_type: string | null;
          is_blocked: boolean;
          blocked_reason: string | null;
          moved_to_column_at: string;
          metadata: Json;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: Omit<
          Database["public"]["Tables"]["kanban_cards"]["Row"],
          "id" | "created_at" | "updated_at" | "moved_to_column_at"
        >;
        Update: Partial<
          Database["public"]["Tables"]["kanban_cards"]["Insert"]
        >;
      };
      calendar_items: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          type: "event" | "delivery" | "creation" | "task" | "meeting";
          status: "pending" | "in_progress" | "completed" | "cancelled";
          start_time: string;
          end_time: string | null;
          all_day: boolean;
          created_by: string;
          responsible_user_id: string | null;
          content_type: string | null;
          platforms: string[];
          color: string | null;
          location: string | null;
          kanban_card_id: string | null;
          post_id: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: Omit<
          Database["public"]["Tables"]["calendar_items"]["Row"],
          "id" | "created_at" | "updated_at"
        >;
        Update: Partial<
          Database["public"]["Tables"]["calendar_items"]["Insert"]
        >;
      };
      calendar_item_connections: {
        Row: {
          id: string;
          source_item_id: string;
          target_item_id: string;
          connection_type: string | null;
          notes: string | null;
          created_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["calendar_item_connections"]["Row"],
          "id" | "created_at"
        >;
        Update: Partial<
          Database["public"]["Tables"]["calendar_item_connections"]["Insert"]
        >;
      };
      calendar_item_comments: {
        Row: {
          id: string;
          calendar_item_id: string;
          user_id: string;
          comment_text: string;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: Omit<
          Database["public"]["Tables"]["calendar_item_comments"]["Row"],
          "id" | "created_at" | "updated_at"
        >;
        Update: Partial<
          Database["public"]["Tables"]["calendar_item_comments"]["Insert"]
        >;
      };
      user_notification_settings: {
        Row: {
          id: string;
          user_id: string;
          calendar_reminders_enabled: boolean;
          calendar_reminder_days: number[];
          calendar_reminder_time: string;
          daily_summary_enabled: boolean;
          daily_summary_time: string;
          weekly_summary_enabled: boolean;
          weekly_summary_day: number;
          weekly_summary_time: string;
          monthly_summary_enabled: boolean;
          monthly_summary_day: number;
          monthly_summary_time: string;
          urgent_alerts_enabled: boolean;
          deadline_alerts_enabled: boolean;
          assignment_alerts_enabled: boolean;
          group_reports_enabled: boolean;
          reminders_enabled: boolean;
          quiet_hours_enabled: boolean;
          quiet_hours_start: string;
          quiet_hours_end: string;
          timezone: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["user_notification_settings"]["Row"],
          "id" | "created_at" | "updated_at"
        >;
        Update: Partial<
          Database["public"]["Tables"]["user_notification_settings"]["Insert"]
        >;
      };
      mike_config: {
        Row: {
          id: string;
          enabled_groups: Json;
          agent_trigger_names: string[];
          group_session_timeout_minutes: number;
          group_memory_hours_back: number;
          group_memory_max_messages: number;
          group_memory_retention_days: number;
          personality_tone: string;
          personality_emoji_level: string;
          default_ai_model: string;
          fallback_ai_model: string;
          max_output_tokens: number;
          bot_phone_number: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["mike_config"]["Row"],
          "id" | "created_at" | "updated_at"
        >;
        Update: Partial<
          Database["public"]["Tables"]["mike_config"]["Insert"]
        >;
      };
      // TODO: Run `npm run db:types` to generate complete types
      // after applying all Supabase migrations
    };
    Views: {};
    Functions: {};
    Enums: {
      calendar_item_type: "event" | "delivery" | "creation" | "task" | "meeting";
      calendar_item_status: "pending" | "in_progress" | "completed" | "cancelled";
      card_type: "single_post" | "campaign";
      post_status: "draft" | "awaiting_approval" | "approved" | "scheduled" | "published" | "failed" | "rejected";
      post_type: "image" | "video" | "carousel" | "story" | "reels" | "short" | "newsletter";
      asset_type: "image" | "video" | "audio" | "document" | "template";
      asset_source: "upload" | "ai_generated" | "emusys" | "canva" | "event";
      approval_status: "pending" | "approved" | "rejected" | "needs_revision";
      campaign_type: "organic" | "paid_social" | "paid_search" | "mixed";
      campaign_status: "draft" | "active" | "paused" | "completed" | "cancelled";
      execution_status: "queued" | "running" | "completed" | "failed" | "cancelled";
      log_level: "debug" | "info" | "warning" | "error" | "critical";
      notification_type: "whatsapp" | "email" | "in_app" | "push";
      notification_priority: "low" | "normal" | "high" | "urgent";
    };
  };
}
